// default chrome arguments if launched internal
export const chromeArgs = [
  "--headless",
  "--no-sandbox",
  "--hide-scrollbars",
  "--mute-audio",
  "--no-first-run",
  "--remote-debugging-address=0.0.0.0",
  "--remote-debugging-port=9222",
  "--max-wait-for-load=2500",
  "--allow-running-insecure-content",
  "--autoplay-policy=user-gesture-required",
  "--ignore-certificate-errors",
  "--no-default-browser-check",
  "--metrics-recording-only",
  "--disable-default-apps",
  "--disable-storage-reset",
  "--disable-dev-shm-usage",
  "--disable-domain-reliability",
  "--disable-component-update",
  "--disable-sync",
  "--disable-notifications",
  "--disable-accelerated-video-decode",
  "--disable-client-side-phishing-detection",
  "--disable-setuid-sandbox",
  "--disable-hang-monitor",
  "--disable-features=ScriptStreaming,TranslateUI,BlinkGenPropertyTrees",
  "--disable-threaded-animation",
  // "--disable-threaded-compositing",
  "--enable-background-thread-pool",
];
